#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export ANSIBLE_VAULT_PASSWORD_FILE=~/.vault_pass
export WORKON_HOME=$HOME/python-venv
export XEUSER=XE67334
export GITSTATUS_LOG_LEVEL=DEBUG
export GOROOT=/usr/local/go
export GOPATH=$HOME/go

if grep -i ubuntu /etc/os-release > /dev/null; then
  source /usr/share/virtualenvwrapper/virtualenvwrapper.sh
elif grep -i fedora /etc/os-release > /dev/null ; then
  source /usr/bin/virtualenvwrapper.sh
fi
